#!/usr/bin/env bash
# configures a server to begin listening on port 80 of all active IPv4 IPs
sudo sed -i "s/8080/80/" /etc/nginx/sites-enabled/default
sudo service nginx restart
echo "" | sudo dd status=none of=/run/nginx.pidi
